<?php

namespace Database\Seeders;

use App\Models\DisplaySetting;
use Illuminate\Database\Seeder;

class HeaderSettingsSeeder extends Seeder
{
    public function run(): void
    {
        $headerSettings = [
            // Top Bar Settings
            [
                'key' => 'show_top_bar',
                'value' => true,
                'type' => 'boolean',
                'title' => 'Показувати верхню панель',
                'description' => 'Відображати верхню панель з контактами та промо',
                'group' => 'header_top_bar',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'key' => 'header_phone',
                'value' => '+380 XX XXX XX XX',
                'type' => 'string',
                'title' => 'Телефон в header',
                'description' => 'Номер телефону для відображення в header',
                'group' => 'header_top_bar',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'key' => 'header_email',
                'value' => 'info@simpleshop.com',
                'type' => 'string',
                'title' => 'Email в header',
                'description' => 'Email адреса для відображення в header',
                'group' => 'header_top_bar',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'key' => 'header_working_hours',
                'value' => 'ПН-НД: 9:00-21:00',
                'type' => 'string',
                'title' => 'Графік роботи',
                'description' => 'Часи роботи для відображення в header',
                'group' => 'header_top_bar',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'key' => 'header_promo_text',
                'value' => 'БЕЗКОШТОВНА ДОСТАВКА ВІД 1500₴',
                'type' => 'string',
                'title' => 'Промо текст',
                'description' => 'Текст промо-акції в header',
                'group' => 'header_top_bar',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'key' => 'header_promo_amount',
                'value' => 1500,
                'type' => 'integer',
                'title' => 'Сума безкоштовної доставки',
                'description' => 'Мінімальна сума для безкоштовної доставки',
                'group' => 'header_top_bar',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'key' => 'show_social_links',
                'value' => true,
                'type' => 'boolean',
                'title' => 'Показувати соціальні мережі',
                'description' => 'Відображати іконки соціальних мереж',
                'group' => 'header_top_bar',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'key' => 'facebook_url',
                'value' => 'https://facebook.com/simpleshop',
                'type' => 'string',
                'title' => 'Facebook URL',
                'description' => 'Посилання на сторінку Facebook',
                'group' => 'header_top_bar',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'key' => 'instagram_url',
                'value' => 'https://instagram.com/simpleshop',
                'type' => 'string',
                'title' => 'Instagram URL',
                'description' => 'Посилання на сторінку Instagram',
                'group' => 'header_top_bar',
                'is_active' => true,
                'sort_order' => 9,
            ],

            // Main Header Settings
            [
                'key' => 'logo_type',
                'value' => 'text',
                'type' => 'string',
                'title' => 'Тип логотипу',
                'description' => 'Тип логотипу: text або image',
                'group' => 'header_main',
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'key' => 'logo_text',
                'value' => 'SIMPLESHOP',
                'type' => 'string',
                'title' => 'Текст логотипу',
                'description' => 'Текст логотипу сайту',
                'group' => 'header_main',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'key' => 'menu_catalog_text',
                'value' => 'КАТАЛОГ',
                'type' => 'string',
                'title' => 'Текст кнопки Каталог',
                'description' => 'Текст кнопки каталогу в меню',
                'group' => 'header_main',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'key' => 'menu_brands_text',
                'value' => 'БРЕНДИ',
                'type' => 'string',
                'title' => 'Текст кнопки Бренди',
                'description' => 'Текст кнопки брендів в меню',
                'group' => 'header_main',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'key' => 'menu_specials_text',
                'value' => 'АКЦІЇ',
                'type' => 'string',
                'title' => 'Текст кнопки Акції',
                'description' => 'Текст кнопки акцій в меню',
                'group' => 'header_main',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'key' => 'menu_help_text',
                'value' => 'ДОПОМОГА',
                'type' => 'string',
                'title' => 'Текст кнопки Допомога',
                'description' => 'Текст кнопки допомоги в меню',
                'group' => 'header_main',
                'is_active' => true,
                'sort_order' => 15,
            ],

            // Mega Menu Settings
            [
                'key' => 'enable_mega_menu',
                'value' => true,
                'type' => 'boolean',
                'title' => 'Увімкнути мега-меню',
                'description' => 'Показувати мега-меню при hover на каталог',
                'group' => 'navigation',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'key' => 'mega_menu_columns',
                'value' => 4,
                'type' => 'integer',
                'title' => 'Кількість колонок мега-меню',
                'description' => 'Кількість колонок в основному мега-меню',
                'group' => 'navigation',
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'key' => 'mega_menu_subcategories_limit',
                'value' => 6,
                'type' => 'integer',
                'title' => 'Ліміт підкатегорій',
                'description' => 'Максимум підкатегорій в одній колонці',
                'group' => 'navigation',
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'key' => 'show_mega_menu_promo',
                'value' => true,
                'type' => 'boolean',
                'title' => 'Показувати промо-блок',
                'description' => 'Відображати промо-блок в мега-меню',
                'group' => 'navigation',
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'key' => 'mega_menu_promo_title',
                'value' => 'АКЦІЇ ТИЖНЯ',
                'type' => 'string',
                'title' => 'Заголовок промо-блоку',
                'description' => 'Заголовок промо-блоку в мега-меню',
                'group' => 'mega_menu_content',
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'key' => 'mega_menu_promo_subtitle',
                'value' => 'Знижки до 50% на вибрані категорії',
                'type' => 'string',
                'title' => 'Підзаголовок промо-блоку',
                'description' => 'Підзаголовок промо-блоку в мега-меню',
                'group' => 'mega_menu_content',
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'key' => 'mega_menu_promo_button',
                'value' => 'ПЕРЕГЛЯНУТИ ВСІ',
                'type' => 'string',
                'title' => 'Текст кнопки промо',
                'description' => 'Текст кнопки в промо-блоці мега-меню',
                'group' => 'mega_menu_content',
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'key' => 'mega_menu_phone_label',
                'value' => 'ГАРЯЧА ЛІНІЯ',
                'type' => 'string',
                'title' => 'Мітка телефону',
                'description' => 'Підпис до телефону в мега-меню',
                'group' => 'mega_menu_content',
                'is_active' => true,
                'sort_order' => 23,
            ],

            // Horizontal Menu Settings
            [
                'key' => 'enable_horizontal_menu',
                'value' => true,
                'type' => 'boolean',
                'title' => 'Увімкнути горизонтальне меню',
                'description' => 'Показувати чорну горизонтальну панель з категоріями',
                'group' => 'horizontal_menu',
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'key' => 'horizontal_menu_display_mode',
                'value' => 'horizontal_only',
                'type' => 'string',
                'title' => 'Режим відображення',
                'description' => 'Режим горизонтального меню: catalog_only, horizontal_only, both',
                'group' => 'horizontal_menu',
                'is_active' => true,
                'sort_order' => 25,
            ],
            [
                'key' => 'horizontal_menu_items_limit',
                'value' => 6,
                'type' => 'integer',
                'title' => 'Кількість категорій',
                'description' => 'Максимум категорій в горизонтальному меню',
                'group' => 'horizontal_menu',
                'is_active' => true,
                'sort_order' => 26,
            ],
            [
                'key' => 'horizontal_show_delivery_info',
                'value' => true,
                'type' => 'boolean',
                'title' => 'Показувати інфо про доставку',
                'description' => 'Відображати інформацію про доставку справа',
                'group' => 'horizontal_menu',
                'is_active' => true,
                'sort_order' => 27,
            ],
            [
                'key' => 'horizontal_delivery_text',
                'value' => 'БЕЗКОШТОВНА ДОСТАВКА ВІД 1500₴',
                'type' => 'string',
                'title' => 'Текст інформації про доставку',
                'description' => 'Текст про доставку в горизонтальному меню',
                'group' => 'horizontal_menu',
                'is_active' => true,
                'sort_order' => 28,
            ],

            // Horizontal Mega Menu Settings
            [
                'key' => 'horizontal_enable_mega_menu',
                'value' => true,
                'type' => 'boolean',
                'title' => 'Horizontal мега-меню',
                'description' => 'Увімкнути мега-меню для горизонтального каталогу',
                'group' => 'horizontal_menu',
                'is_active' => true,
                'sort_order' => 29,
            ],
            [
                'key' => 'horizontal_mega_menu_columns',
                'value' => 4,
                'type' => 'integer',
                'title' => 'Колонки horizontal мега-меню',
                'description' => 'Кількість колонок в горизонтальному мега-меню',
                'group' => 'horizontal_menu',
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'key' => 'horizontal_mega_menu_subcategories_limit',
                'value' => 6,
                'type' => 'integer',
                'title' => 'Ліміт підкатегорій horizontal',
                'description' => 'Максимум підкатегорій в горизонтальному мега-меню',
                'group' => 'horizontal_menu',
                'is_active' => true,
                'sort_order' => 31,
            ],
            [
                'key' => 'horizontal_show_mega_menu_promo',
                'value' => true,
                'type' => 'boolean',
                'title' => 'Промо в horizontal мега-меню',
                'description' => 'Показувати промо-блок в горизонтальному мега-меню',
                'group' => 'horizontal_menu',
                'is_active' => true,
                'sort_order' => 32,
            ],
            [
                'key' => 'horizontal_mega_menu_promo_title',
                'value' => 'ШВИДКІ ПОКУПКИ',
                'type' => 'string',
                'title' => 'Заголовок horizontal промо',
                'description' => 'Заголовок промо-блоку горизонтального мега-меню',
                'group' => 'horizontal_menu',
                'is_active' => true,
                'sort_order' => 33,
            ],
            [
                'key' => 'horizontal_mega_menu_promo_subtitle',
                'value' => 'Популярні товари в один клік',
                'type' => 'string',
                'title' => 'Підзаголовок horizontal промо',
                'description' => 'Підзаголовок промо-блоку горизонтального мега-меню',
                'group' => 'horizontal_menu',
                'is_active' => true,
                'sort_order' => 34,
            ],
            [
                'key' => 'horizontal_mega_menu_promo_button',
                'value' => 'ПЕРЕГЛЯНУТИ ХІТИ',
                'type' => 'string',
                'title' => 'Кнопка horizontal промо',
                'description' => 'Текст кнопки промо-блоку горизонтального мега-меню',
                'group' => 'horizontal_menu',
                'is_active' => true,
                'sort_order' => 35,
            ],
        ];

        foreach ($headerSettings as $setting) {
            DisplaySetting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }

        $this->command->info('✅ Header налаштування створені/оновлені');
    }
}
